### ISSUE TITLE
PrettyPrint flag concerning JSON output

### ISSUE THREAD

**Issue by igler** [javers/javers#197] opened 2015-09-14 19:15 UTC
Add configuration option to give user a choice on pretty print or standard.

**Comment by bartoszwalacik** [comment] 2015-09-21 07:39
released in v 1.3.8

**Closed by bartoszwalacik** 2015-09-21 07:39 UTC
Labels: enhancement

**Comment by igler** [comment] 2015-09-21 07:45
Do you have an example how to set this flag or is it documented somewhere?

**Comment by bartoszwalacik** [comment] 2015-09-21 08:43
right, there is a new method in JaversBuilder:
http://javers.org/javadoc_1.3.0/org/javers/core/JaversBuilder.html#withPrettyPrint-boolean-

**Comment by igler** [comment] 2015-09-21 11:22
Thanx, upgraded to the new version and testet it:
<pre><code>@Bean
public Javers javers() {

    JaversSqlRepository sqlRepository = SqlRepositoryBuilder
                .sqlRepository()
                .withConnectionProvider(jpaConnectionProvider())
                .withDialect(DialectName.MYSQL)
                .build();

    return TransactionalJaversBuilder
                .javers()
                .withPrettyPrint(false)
                .withObjectAccessHook(new HibernateUnproxyObjectAccessHook())
                .registerJaversRepository(sqlRepository)
                .registerValueTypeAdapter(new ZonedDateTimeJaversTypeAdapter())
                .build();
}
</code></pre>

 Now the returned string looks like:
<pre><code>"[{\"changeType\":\"ValueChange\",\"globalId\":{\"entity\":\"...</code></pre>

As the return-type in the controller is <code>ResponseEntity&lt;String> getChangesOfLocation(@PathVariable("id") Location location)</code> this is probably OK. But what I'd like to have is a well structured output I normally get when I would use <code>ResponseEntity&lt;List&lt;Change>> getChangesOfLocation(@PathVariable("id") Location location) </code>. The error I get with the <code>ResponseEntity&lt;List&lt;Change>></code> signature is something like:

<pre><code>Could not write content: AFFECTED_CDO_IS_NOT_AVAILABLE JaVers runtime error - affected cdo is not available, you can access it only for freshly generated diffs (through reference chain: java.util.ArrayList[0]->org.javers.core.diff.changetype.ValueChange[\"affectedCdo\"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: AFFECTED_CDO_IS_NOT_AVAILABLE JaVers runtime error - affected cdo is not available, you can access it only for freshly generated diffs (through reference chain: java.util.ArrayList[0]->org.javers.core.diff.changetype.ValueChange[\"affectedCdo\"])",
  "path": "/api/locations/17/changes"</code></pre>

Doing a debug-session I can see that the <code>affectedCdo</code> variable is <code>null</code> Any chance to inject the <code>codId</code> into the <code>Change</code> object before sending it to the <code>ResponseEntity</code> serialization through Spring/Jackson?.

**Comment by bartoszwalacik** [comment] 2015-09-21 21:36
well, so the root cause is, that Jackson cant serialize JaVers Changes to JSON.
I've never tested JaVers with Jackson, we are using Gson but we want Javers to be compatible with spring-mvc, so it do have sense to make JaVers objects beeing Jackson friendly.

I'd prefer if you put a separate issue for that, sth like 'JaVers objects (Change, CdoSnapshot) should be Jackson friendly'.

Now I'm working on backlog for upcoming releases, think that new issue should have high priority ...

**Comment by igler** [comment] 2015-09-22 07:29
OK, opened https://github.com/javers/javers/issues/205 to continue discussion there.
