### ISSUE TITLE
Handle Composite id with IdClass annotation

### ISSUE THREAD

**Issue by bala-striva** [javers/javers#1077] opened 2021-03-18 15:33 UTC
**Clear description of my expectations versus reality**
With Entities having an IdClass annotation and using other Entities as the id, Javers will use the toString of the id entity and not the id property. This could result in a very long InstanceId.
(See the linked test case for an example)

**Steps To Reproduce**
I have a **runnable test case ** which isolates the bug and allows Javers Core Team to easily reproduce it. I have pushed this test case to [my fork of this repository](https://github.com/bala-striva/javers/commits/composit_id_handling_with_idclass):

https://github.com/bala-striva/javers/commit/803d6ae8bed55d852c043a3159a007d15e58b392

**Javers' Version**
5.9.4-master

**Additional context**
With the dehydrate of the composite key values I was able to achieve that the InstanceId to contains only the referenced entities id field and not the toString representation of those entities.

**Comment by bartoszwalacik** [comment] 2021-03-21 13:08
It's not a bug, there is no support for IdClass class in Javers.

**Comment by bartoszwalacik** [comment] 2021-03-24 07:58
fixed in 6.0.0-RC2

**Closed by bartoszwalacik** 2021-03-24 07:58 UTC
Labels: fixed, new feature
