### ISSUE TITLE
findChanges() is not finding changes for a commitId like 101.01

### ISSUE THREAD

**Issue by kjheim** [javers/javers#971] opened 2020-05-20 21:46 UTC
I’m using the current JaVers version 5.9.0 in a Java application using MongoDB.   The app is calling javers.findChanges() but have found it works for a value like 100 but not 101.01.   I am not sure why sometimes we get the Major.Minor number values but those are not coming back with changes from javers.findChanges() query.   These are the values in mongo under ﻿“commitMetadata.id”.    The list of commit ID’s comes from the ﻿‘jv_snapshots’ collection directly using a JPA call in case that relates or some other value should be used.
 
Loop through list of BigDecimal commitId values:
 
QueryBuilder query = QueryBuilder.byClass(MyClass.class)
    .withCommitId(commitId)
    .withChildValueObjects()
    .withNewObjectChanges();
Changes changes = javers.findChanges(query.build());
 
* Tried toCommitId but we only want the one commit and withCommitId overrides toCommitId
* Tried several query options to find these commits

I have not included test cases since still trying to recreate but the example is common to us.

**Comment by bartoszwalacik** [comment] 2020-05-21 15:21
hi, provide a failing test case as described in https://github.com/javers/javers/blob/master/CONTRIBUTING.md

**Comment by kjheim** [comment] 2020-05-21 18:26
@bartoszwalacik, I will try but not fully understanding the commitID generation which creates *.01 conditions in a test case to show the findChanges() not working.  We have found 'javers-spring-boot-starter-mongo'  '5.6.0' is working.  There are comments and prior fixed issues related to sequencing you commented on so wondering if there is a way to product a minor number of 01 during a test so that a test could be created.

**Comment by bartoszwalacik** [comment] 2020-05-21 18:28
minor commitId numbers are generated when multiple threads are committing, so your test should be mulrithreaded

**Comment by cybuch** [comment] 2020-06-02 13:52
Probably it's duplicate of https://github.com/javers/javers/issues/958

**Comment by bartoszwalacik** [comment] 2020-07-16 20:43
@cybuch right, it's duplicate, fixed in 5.10.4

**Closed by bartoszwalacik** 2020-07-16 20:43 UTC
Labels: fixed
