### ISSUE TITLE
AOT Support?

### ISSUE THREAD

**Issue by korkutkose** [javers/javers#1295] opened 2023-06-08 11:16 UTC
As i understood that, currently, neither programatically nor at repository level [https://github.com/oracle/graalvm-reachability-metadata](graalvm-reachability-metadata) JaVers supporting spring-native yet. Is there any plan for this? 
It's cumbersome to extract necessary reflections via tracability agent to be honest since we need to keep hitting necessary endpoints programatically to generate reflection configs.

**Comment by bartoszwalacik** [comment] 2023-07-10 20:24
sorry, but I have zero knowledge about GraalVM, btw this issue is unclear for me. Is it a question? Is it a feature request? If so, please follow the issue template

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

Once an issue is accepted -- we are open for contributions

**Comment by goafabric** [comment] 2023-08-28 06:07
@bartoszwalacik @korkutkose 
Maybe i can shed some light here, as i would have been also interested in native support.
For anyone who stumbles upon this issue.

In a nutshell, AOT/Native support, gives you the option to compile native machine code images, from pure java.
While this has several benefits, the downside is that you need to register so called "hints" for everything the compiler know needs ahead of time, like reflection, proxies etc.

That works good if there will be only a few of these hints.
However, i tried to get the ball running with javers .. and unfortunately as amazingly simple javers works,
i ended up with 100+ reflection hints, it's still not working because of a hibernate problem .. at least it know survives the general bootstrap phase.

I will attach the spring boot Configuration for the sake of clearness.

But it think with so much reflection inside javers, aot is not a good fit for now.
At least it helped me to get a good inspiration how to build my own auditing, based an AOP with Spring data, thx 4 that

**Comment by goafabric** [comment] 2023-08-28 06:07
Native hint config
[JaversNativeConfiguration.java.zip](https://github.com/javers/javers/files/12450824/JaversNativeConfiguration.java.zip)

**Comment by goafabric** [comment] 2023-09-01 06:51
> @goafabric thanks for explanation, btw if you guys are eager to contribute this kind of support to javers -- let me know

we will and thx .. but usually setting and also maintaining 100+ hints does not make a lot of sense

**Comment by goafabric** [comment] 2024-11-05 07:52
so for everyone stumbling here i can provide the file below it lakes make everything bootstrap and write
for current boot 3.3.5 and javers 7.6.3

[JaversNativeConfiguration.java.zip](https://github.com/user-attachments/files/17628885/JaversNativeConfiguration.java.zip)

**Comment by bartoszwalacik** [comment] 2024-11-05 19:12
sure @goafabric , I will review it

**Comment by bartoszwalacik** [comment] 2024-11-15 08:16
PR with AOT support 
https://github.com/javers/javers/pull/1421

**Comment by goafabric** [comment] 2024-11-15 08:23
big thx 4 merging

**Comment by bartoszwalacik** [comment] 2024-11-17 20:18
released in 7.7.0
thanks @goafabric

**Closed by bartoszwalacik** 2024-11-17 20:18 UTC
Labels: fixed - waiting to be released
