### ISSUE TITLE
Current State of Documents and Performence Issues

### ISSUE THREAD

**Issue by Kira-Cesonia** [javers/javers#992] opened 2020-06-24 11:01 UTC
This might be two different things, but I'd have a hard time describing them separately, so I'll put it into one ticket now.

The bottom line is, we have a medium-sized object hierarchy that represents a medium-sized ReqIF-File (~1,000 lines). The Data Model representing this is reasonably complex and contains over a hundred different classes. Even so, when saving and loading that object-hierarchy to MongoDB using the Mongo Driver, it only takes about 100ms or so.

By contrast, when I use Javers, all operations - be they reading or writing - take 2 to 3 **seconds**. That's an increase by the factor 20.

Now, while I can understand that building the snapshots when committing data takes time, the real problem is the way that (as I understand it) Javers handles data retrieval. If I understand it correctly, then Javers builds the most recent object by getting the base object, and then applying all changes ever to it. That appears to be what results in the unacceptable load time even for the first revision of a medium-sized ReqIF File. I dread to think about how long it would take to retrieve data for a production-size ReqIF file (I have a real-world example here that has over 60,000 lines), with maybe100 changes being made to it each day. I fear the retrieval time would be measured in days, if not years.

Another issue I had is that I could not find a method that would simply fetch me the latest state of all saved objects. I know I can get the earliest version like this:

`JqlQuery entryQuery = QueryBuilder.byClass(ReqIf.class).withVersion(1).build();`

However, there does not appear to be an "inverse to this, such as maybe:

`JqlQuery entryQuery = QueryBuilder.byClass(ReqIf.class).withVersion(-1).build();`

or:

`JqlQuery entryQuery = QueryBuilder.byClass(ReqIf.class).withLatestVersion().build();`

And as I gather it, this, too is directly linked to Javers not storing the most recent version of an object.

To counteract both those issues, I propose implementing a functionality that will store the most recent version of an object in the database in such a form that:

Initial Version + All Changes = Latest Version

That would completely eliminate the performance issue while reading, and also allow for easy implementation of requests for the latest versions of documents. The added cost would be to have two full copies of each document in the database. But that, I think, is an acceptable cost considering that even the production-size ReqIF is only 3MB big, and especially since getting the most recent version of an object is pretty much the default use case (wheras quering versioning information or loading previous states of objects probably make up for only about 10% or less of all requests in any use cases).

A different approach achieving the same thing but without the additional space requirements would be to store _only_ the most recent version, and reverse-construct previous versions by means of changes. That would probably be more complicated to implement though.

**Comment by bartoszwalacik** [comment] 2020-06-24 11:58
Hi, well, quite a long story. First of all, the only thing Javers stores in DB are object snapshots. The latest snapshot is simply a snapshot with latest commit date, it's fetched from DB with a single query. It's dead simple design. I don't know why you are suggesting that `Javers not storing the most recent version of an object`. It's not true.

There is no method to load all latest snapshots from DB.
Loading almost whole database to your jvm memory is rarely possible. But you can easily load the latest snapshot of a given object. If you need to browse the latest data of all objects, simply use your applications' database. Javers is designed to browse history of a given object. It's not a general purpose SQL-like database.

If you are experiencing performance issues, it's caused by the size of your commits. If your commit contains 1000 objects, it wont be fast, because it means 1000 DB queries (to check existing latest snapshots) and potentially 1000 DB inserts (to insert new latest snapshots if objects are changed).

Try to limit the depth of the our object graph being committed , there are various ways, see https://javers.org/documentation/domain-configuration/#ignoring-things

**Closed by bartoszwalacik** 2020-06-24 11:58 UTC

**Comment by Kira-Cesonia** [comment] 2020-06-25 04:54
The point being here is that when I retrieve an object and its sub-objects in Javers, it takes about 20 times as long as using MongoDB Driver, because the Objects in Javers are fragmented, whereas using MongoDB Driver, the whole Object and all sub-objects are just stored as one document. Thus, when I want to get a version of a document in Javers that's a 1000 DB Accesses, whereas with MongoDB Driver it's just one.

Now I understand that fragmenting the document helps keep the commit size small in the long run (although in the short run (that is for one commit), the jv_snapshots collection here is 1,500KB big with 1.200 documents, while a MongoDB Driver created collection storing that same data is only 90KB big and has 1 document), so I perfectly understand why it's done, and I also think it's okay to deal with these long access times in versioning.

I just don't think they are acceptable when dealing with the most-common day-to-day use case of just wanting to get the latest state of the object. As such, something I direly miss in Javers is a jv_current collection that simply has a no-frills version of the latest states of the committed objects, unfragmented and thus packed into a single document, so they can be accessed by a single DB access.

In fact, that is precisely what I'm doing with out project now. I'm sort of piling the old MongoDB Logic on top of the Javers logic to create Javers EXP, which allows just this sort of behavior. I guess what I'm trying to say is that I feel that Javers should support this behaviour out of the box, since wanting to access the most recent data fast is the most common use case in any project.

**Comment by Kira-Cesonia** [comment] 2020-06-25 07:11
To further illustrate this, I have created a simple test for reading a basic-yet-numerous object from Mongo using both Javers and Mongo Driver.

The Object in question looks like this:

```
@TypeName("Legion")
public class Legion {
	@Id
	public int _id;
	public List<Company> companies;
	
	public Legion() {
		
	}
	
	public Legion(int legionId, List<Company> companies) {
		this._id = legionId;
		this.companies = companies;
	}
}

@TypeName("Company")
public class Company {
	public int legionId;
	public int companyId;
	public List<Legionnaire> legionnaires;
	
	public Company() {
		
	}
	
	public Company(int legionId, int companyId, List<Legionnaire> legionnaires) {
		this.legionId = legionId;
		this.companyId = companyId;
		this.legionnaires = legionnaires;
	}
}

@TypeName("Legionnaire")
public class Legionnaire {
	public int legionnaireId;
	public int legionId;
	public int companyId;
	
	public Legionnaire() {
		
	}
	
	public Legionnaire(int legionId, int companyId, int legionnaireId) {
		this.legionId = legionId;
		this.companyId = companyId;
		this.legionnaireId = legionnaireId;
	}
}
```

I'm tasting this with 100 legions that have 100 legionnaires each, so 10,000 objects in total. The tests are as follows:

```
package legion;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import com.mongodb.MongoClient;

import dataObjects.legion.Company;
import dataObjects.legion.Legion;
import dataObjects.legion.LegionFactory;
import exceptions.DatabaseNotConnectedException;
import mongoDB.MongoDB_Connection;

class LegionMongoDbReaderTest {
	
	private static final int TEST_LEGION_ID = 0;
	private static final int COMPANY_COUNT = 100;
	private static final int LEGIONNAIRES_PER_COMPANY = 100;
	private static LegionMongoDbReader legionReader;
	private static LegionMongoDbWriter legionWriter;
	
	@BeforeAll
	static void setUpLegionReader() throws DatabaseNotConnectedException {
		MongoDB_Connection mongoDB_connection = new MongoDB_Connection();
		MongoClient mongoDatabaseConnectionPool = mongoDB_connection.mongoDatabaseConnectionPool;
		legionReader = new LegionMongoDbReader(mongoDatabaseConnectionPool);
		legionWriter = new LegionMongoDbWriter();
		legionWriter.legionDatabase.drop();
		Legion testLegion = LegionFactory.createLegion(
			TEST_LEGION_ID,
			COMPANY_COUNT,
			LEGIONNAIRES_PER_COMPANY
		);
		legionWriter.writeLegionToMongoDB(testLegion);
		legionWriter.writeLegionToJavers(testLegion);
	}

	@Test
	void readLegionFromMongoDbByIdShouldReturnLegionWithCorrectCompanyCount() {
		Legion testLegion = legionReader.readLegionFromMongoDbById(TEST_LEGION_ID);
		
		assertEquals(COMPANY_COUNT, testLegion.companies.size());
	}
	
	@Test
	void readLegionFromMongoDbByIdShouldReturnLegionWithCorrectNumberOfLegionnaires() {
		Legion testLegion = legionReader.readLegionFromMongoDbById(TEST_LEGION_ID);
		
		int actualLegionnaireCount = 0;
		for(Company company : testLegion.companies) {
			actualLegionnaireCount += company.legionnaires.size();
		}
		
		assertEquals(COMPANY_COUNT * LEGIONNAIRES_PER_COMPANY, actualLegionnaireCount);
	}
	
	@Test
	void readLegionFromJaversByIdShouldReturnLegionWithCorrectCompanyCount() {
		Legion testLegion = legionReader.readLegionFromJaversById(TEST_LEGION_ID);
		
		assertEquals(COMPANY_COUNT, testLegion.companies.size());
	}
	
	@Test
	void readLegionFromJaversByIdShouldReturnLegionWithCorrectNumberOfLegionnaires() {
		Legion testLegion = legionReader.readLegionFromJaversById(TEST_LEGION_ID);
		
		int actualLegionnaireCount = 0;
		for(Company company : testLegion.companies) {
			actualLegionnaireCount += company.legionnaires.size();
		}
		
		assertEquals(COMPANY_COUNT * LEGIONNAIRES_PER_COMPANY, actualLegionnaireCount);
	}
}
```

The test durations are as follows:
(Note that the writing part is not part of the tests, so its duration does not contribute to the metrics)

* readLegionFromMongoDbByIdShouldReturnLegionWithCorrectCompanyCount: 0,034 s
* readLegionFromMongoDbByIdShouldReturnLegionWithCorrectNumberOfLegionnaires: 0,047 s
* readLegionFromJaversByIdShouldReturnLegionWithCorrectCompanyCount: 21,829 s
* readLegionFromJaversByIdShouldReturnLegionWithCorrectNumberOfLegionnaires: 19,825 s
** Also, this test fails with an error "java.lang.ClassCastException: class com.google.gson.internal.LinkedTreeMap cannot be cast to class dataObjects.legion.Company (com.google.gson.internal.LinkedTreeMap and dataObjects.legion.Company are in unnamed module of loader 'app')", but that is beyond the scope of this ticket

This serves nicely to illustrate my problem. Although both Javers and the MongoDB driver read (error notwithstanding) the same data from the database, Javers takes 400-600 times longer due to breaking down the object into individual documents, while the MongoDB Driver simply stores the most recent object as one document.

Again, I fully understand that storing the objects as snapshots is great for versioning, and I understand that "reverse constructing" a document from snapshots takes time. That's not the problem. The problem is that the most common usecase - namely getting the most recent version of a document - should be a fast operation, and that it _is_ a fast operation when using MongoDB Driver. An obvious solution exists too, namely storing the most recent version of an object as one document, without breaking it down into snapshots. And I feel Javers should support that.

For reference, all files I used to generate these statistics can be found in the following Github Repository:
https://github.com/Kira-Cesonia/MongoDBVersioningTest/tree/CKNG-83-versioning-expedition-javers
The test file above is located in /src/test/java/legion/

**Comment by bartoszwalacik** [comment] 2020-06-25 21:38
I totally agree that "that the most common use case - namely getting the most recent version of a document - should be a fast operation". But it's not the Javers' job. It's the job of your applications' database aided with the classic Mongo Template, Spring Data or whatever solution you use for persistence.

I don't understand why you want Javers to do the applications' database job. Javers is not a replacement for your applications' database and your whole persistence layer. It's an add-on for versioning and tracking changes in selected objects which are important for your business.

Of course we always can talk about improving performance of Javers. 
Embedding sub-objects in parent object snapshot (in Javers language we would say: embedding child Value Objects in owning Entity snapshot) is a valid option.
It's a great idea. In your case, it would improve performance of Javers' commits. But in the same time it would seriously increase the storage size. For now, Javers snapshots are fine grained, one object = one db snapshot.
So even if you have 1000 objects in your objects graph and you change just one of them, Javers will save only one small snapshot. Javers saves snapshots only for **changed** objects. This data model saves your storage.

In your solution, changing one field in one object which is a part of huge objets graph would result in saving snapshot of the whole graph. I agree that it would be faster but it also would mean much more storage requirements.

**Comment by Kira-Cesonia** [comment] 2020-06-26 05:05
> I don't understand why you want Javers to do the applications' database job. Javers is not a replacement for your applications' database and your whole persistence layer. It's an add-on for versioning and tracking changes in selected objects which are important for your business.

Well, you say that now, but apparently my impression of what Javers was intended to be was different. I got that impression from looking at the Javers homepage and from a certain StackOverflow response, and even while working with it and up until you explicitly mentioned that that's not what Javers is supposed to be right now, that impression stuck around. I suppose that's because I sort of expect this kind of functionality from a versioning framework.

You can probably tell I put a lot of thought into this over the last week or so, and thus I came up with a concept for a solution that should work nicely at least in my case, and maybe in a couple of other cases. The idea is to build on the Javers Diffs to efficiently track changes even in large documents with only minimal effort by having an original, a current, and a delta document per object. Even if the object is large, the individual deltas should be small, and like this any version of an object can be restored using two database accesses. I still have to experiment to see if it works in practice though. If you like, you can follow my experiments here: https://github.com/Kira-Cesonia/tri-JaDe

Cheers, and thank you for all your hard work =^,^=
