### ISSUE TITLE
bug of getChangeHistory?

### ISSUE THREAD

**Issue by edenchen123** [javers/javers#137] opened 2015-04-13 09:44 UTC
Sample code to compare 2 objects,but getChangeHistory can not print out the value object change
   
       Javers javers = JaversBuilder.javers().build();

        Person tommy = new Person("tommy", "Tommy Smart");
        Address address1 = new Address("NY", "5th street");
        tommy.setAddress(address1);

        javers.commit("eden", tommy);

        Person tommy2 = new Person("tommy", "Tommy 2");
        Address address2 = new Address("NY", "7th street");
        tommy2.setAddress(address2);

        javers.commit("eden", tommy2);

        Diff diff = javers.compare(tommy, tommy2);
        System.out.println(diff.toString());
        System.out.println();

        List<Change> changes = javers.getChangeHistory(InstanceIdDTO.instanceId("tommy", Person.class), 2);
        String changeLog = javers.processChangeList(changes, new SimpleTextChangeLog());

        System.out.println(changeLog);

output:

Diff:
1. ValueChange{globalId:'Person/tommy#address', property:'street', oldVal:'5th street', newVal:'7th street'}
2. ValueChange{globalId:'Person/tommy', property:'name', oldVal:'Tommy Smart', newVal:'Tommy 2'}

commit 2.0, author: eden, Apr 13, 2015 5:41:16 PM
  changed object: Person/tommy
    value changed on 'name' property: 'Tommy Smart' -> 'Tommy 2'
commit 1.0, author: eden, Apr 13, 2015 5:41:16 PM
    new object: Person/tommy

**Comment by bartoszwalacik** [comment] 2015-04-14 09:46
Hi, currently we are doing a major rework of Repository querying API. The new API is called JQL (Javers Query Language). You can test using latest snnapshot
1.1.2-SNAPSHOT
https://oss.sonatype.org/content/repositories/snapshots/

Could you please try if the problem also occures when using new API?

```javers.findChanges(JqlQuery query)'```

**Comment by edenchen123** [comment] 2015-04-14 14:56
that's amazing, I will test with the new snapshot, and let you know

**Comment by edenchen123** [comment] 2015-04-17 09:22
same as before and there are a lot of null -->

commit 2.0, author: eden, Apr 17, 2015 5:21:55 PM
  changed object: Person/tommy
    value changed on 'name' property: 'Tommy Smart' -> 'Tommy 2'
commit 1.0, author: eden, Apr 17, 2015 5:21:54 PM
  changed object: Person/tommy
    value changed on 'login' property: 'null' -> 'tommy'
    value changed on 'name' property: 'null' -> 'Tommy Smart'
    reference changed on 'address2' property: 'null' -> 'Person/tommy#address2'

**Comment by bartoszwalacik** [comment] 2015-04-18 07:05
yes, these null are actualy here by design. This is a new feature in JQL version, you get the 'initial change' (from the first commit) which is a change from nothing to something.

Not clear for me what is your issue? Do you want to list changes on Address ValueObject?
If so use:
`javers.findChanges( QueryBuilder.byValueObjectId(2, Person.class, "address").build() );`

**Comment by bartoszwalacik** [comment] 2015-04-29 20:48
JQL is released in javers 1.2.0
take a look at new query API and examples
http://javers.org/documentation/jql-examples/#new-object-filter

now you can turn on/of initial changes for change query

**Closed by bartoszwalacik** 2015-04-29 20:48 UTC
Labels: JQL, question
