### ISSUE TITLE
JaversSpringDataAuditableRepositoryAspect always gets highest precedence as it has no @Order annotation.

### ISSUE THREAD

**Issue by K10Codes** [javers/javers#981] opened 2020-06-11 08:10 UTC
To be able to add some custom logic before javers can finally audit the data by using '@AfterReturning' advices from 'JaversSpringDataAuditableRepositoryAspect.java' , it is needed for these advices to run after the custom ones. Since @After advices run in reverse order. so if we explicitly define @Order(0) on this aspect then we can add our custom aspects and give them an @Order(n>0).
One use case is if for some repository only certain type of data is to be audited, then we can filter the data in our custom aspect and then pass to the javers aspect to audit.

**Comment by bartoszwalacik** [comment] 2020-06-13 20:51
fixed in 5.9.2

**Closed** 2020-06-13 20:51 UTC
Labels: fixed

**Comment by K10Codes** [comment] 2020-06-15 07:03
I saw this change merge in with 5.9.2. However, it also included a lot of changes corresponding to #985. It now doesn't work for previous mongo versions as it doesn't find a bean for MongoClient. Can we create two separate releases for both of these changes?

**Comment by bartoszwalacik** [comment] 2020-06-15 07:07
Two separate Javers variants just to cover a package rename in MongoClient? No, we can't do this.

**Comment by bartoszwalacik** [comment] 2020-06-15 07:17
As far as I understand this situation, the whole mess is caused by Mongo guys, who decided to to rename `com.mongodb.MongoClient` to `com.mongodb.client.MongoClient`.  For a while, both classes were present in the `mongodb-driver` jar. Since 4.x, they removed `com.mongodb.MongoClient`, so we can't support both versions, is it correct?

**Comment by bartoszwalacik** [comment] 2020-06-15 10:15
I will try to fix this issue in 5.9.3

**Comment by K10Codes** [comment] 2020-06-15 12:14
> As far as I understand this situation, the whole mess is caused by Mongo guys, who decided to to rename `com.mongodb.MongoClient` to `com.mongodb.client.MongoClient`. For a while, both classes were present in the `mongodb-driver` jar. Since 4.x, they removed `com.mongodb.MongoClient`, so we can't support both versions, is it correct?

I agree, i was thinking that issue #985 seems to be an update for javers in terms of its spring and mongo versions and the release corresponding to that also had fix for this issue.(i.e changing the order of aspects).  So, if we release them separately, like 5.9.2 (for aspect order fix) and 5.9.3 ( for dependency changes). We can then support that javers 5.9.3 and above would work only with mongo 4 and above.  In my opinion any update release should be a standalone release with nothing else going in with it. I was hoping to get the issue fix worked out with my current application stack which is mongo 3.x and it would be a major change to upgrade mongo to 4.x for us to support the change.

**Comment by K10Codes** [comment] 2020-06-15 12:26
> I will try to fix this issue in 5.9.3

I saw this change and i think with this you are trying to support both MongoClient classes, in the initJaversMongoDatabase  method. From the javers doc i was running javers in my application by providing a bean for javers as :
@Bean
    public Javers javers() {
        MongoRepository javersMongoRepository = new MongoRepository(mongoClient.getDatabase(mongoConfigProperties.getDataBaseName()));
        return JaversBuilder.javers().registerJaversRepository(javersMongoRepository).build();
    }
and because of this bean that i provide the initJaversMongoDatabase doesn't get called. So should i then stop creating this bean on my own then ?

**Comment by bartoszwalacik** [comment] 2020-06-15 13:14
well, I have done this fix in `JaversMongoAutoConfiguration` in the `javers-spring-boot-starter-mongo` which has to play along with `spring-boot-starter-data-mongodb`, which provides `com.mongodb.MongoClient` or `com.mongodb.client.MongoClient` bean.

When you are using these Spring Boot starters, all Javers' beans are created automatically.

**Comment by bartoszwalacik** [comment] 2020-06-15 13:20
5.9.3 should be available soon in Central, let me know if it fixes your issue (assuming that you are are using the old MongoClient)

**Comment by K10Codes** [comment] 2020-06-15 13:59
Thanks for the update @bartoszwalacik . I tried to pull this branch and built it locally but i am getting  I get this exception java.lang.NoSuchMethodError: com.mongodb.client.MongoCollection.insertOne(Ljava/lang/Object;) from org.javers.repository.mongo.MongoRepository.lambda$persistSnapshots$3. when javers tries to capture audit change for an entity. I am not sure what is causing this.

**Comment by bartoszwalacik** [comment] 2020-06-15 14:56
Please try 5.9.3 from Central
