### ISSUE TITLE
Abandoned connections after schema validation

### ISSUE THREAD

**Issue by dbacinski** [javers/javers#576] opened 2017-08-01 12:59 UTC
During app startup Javers is validating if database schema is correct.

When i have enable logging of abandoned connections I am getting a stack trace from Javers, like this:
```
WARNING: Connection has been abandoned PooledConnection[org.postgresql.jdbc.PgConnection@56e64c5]:java.lang.Exception
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getThreadDump(ConnectionPool.java:1102)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:807)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:651)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:151)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
	at info.stsa.maint.config.JaversConnectionProvider.getConnection(JaversConnectionProvider.kt:10)
	at org.javers.repository.sql.SqlRepositoryBuilder$1.getConnection(SqlRepositoryBuilder.java:77)
	at org.polyjdbc.core.transaction.ExternalTransactionManager.openTransaction(ExternalTransactionManager.java:18)
	at org.polyjdbc.core.schema.SchemaManagerFactory.createManager(SchemaManagerFactory.java:44)
	at org.polyjdbc.core.DefaultPolyJDBC.schemaManager(DefaultPolyJDBC.java:74)
	at org.javers.repository.sql.schema.JaversSchemaManager.ensureSchema(JaversSchemaManager.java:39)
	at org.javers.repository.sql.JaversSqlRepository.ensureSchema(JaversSqlRepository.java:88)
	at org.javers.core.JaversBuilder.build(JaversBuilder.java:113)
	at info.stsa.maint.config.MaintenanceDataSourceConfiguration.maintJavers(MaintenanceDataSourceConfiguration.kt:126)
```
This is how connection provider is implemented, I am using Spring Boot 2.0.0.M2:
```
class JaversConnectionProvider(val dataSource: DataSource) : org.javers.repository.sql.ConnectionProvider {

    override fun getConnection(): Connection =
            DataSourceUtils.getConnection(dataSource)
}
```
For regular cases I can use `@Transactional` which is closing connection for me.

Is there a way to close connections which are opened during app startup?

**Comment by bartoszwalacik** [comment] 2017-08-01 13:12
This part of javers code looks fine

```
    public void ensureSchema() {
        this.schemaInspector = polyJDBC.schemaInspector();
        this.schemaManager = polyJDBC.schemaManager();

        for (Map.Entry<String, Schema> e : schemaFactory.allTablesSchema(dialect).entrySet()) {
            ensureTable(e.getKey(), e.getValue());
        }

        alterCommitIdColumnIfNeeded(); // JaVers 2.5 to 2.6 schema migration

        if(this.dialect instanceof MsSqlDialect) {
            alterMssqlTextColumns();
        }

        TheCloser.close(schemaManager, schemaInspector);
    }
```

could you push a failing test case with a reproduction scenario?

**Comment by bartoszwalacik** [comment] 2017-11-02 17:57
closing due to lack of activity

**Comment by IlyaNerd** [comment] 2020-12-23 13:20
@bartoszwalacik the issue still exists and deeper, when getting the connection, it doesnt close it in finally or twr
`    private boolean executeSQL(String sql) {
        try {
            Statement stmt = connectionProvider.getConnection().createStatement();

            logger.info("executing schema migration SQL:\n" + sql);

            boolean b = stmt.execute(sql);
            stmt.close();

            return b;
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }`

**Closed** 2020-12-26 21:10 UTC
Labels: test case required

**Comment by bartoszwalacik** [comment] 2020-12-26 21:12
@IlyaNerd Connections are managed by an application, typically in a connection pool. They should not be closed by Javers. 

please push a failing test case with a reproduction scenario
