### ISSUE TITLE
Support for SpringBoot 3.0.0

### ISSUE THREAD

**Issue by smeligrana** [javers/javers#1238] opened 2022-12-05 19:02 UTC
I tried using javers with spring boot 3.0.0 but first it gave me a conflict with hibernate libraries, after resolving the conflict the javers bean is not created.

Are you considering a version compatible with spring boot 3.0.0?

Thanks

**Comment by bartoszwalacik** [comment] 2022-12-06 07:16
I will try to bump Spring version before Xmass

**Comment by nicolo-paganin** [comment] 2023-01-03 12:27
Hi @bartoszwalacik, any news for support for SpringBoot 3.0.0?
thanks

**Comment by bartoszwalacik** [comment] 2023-01-03 12:31
still thinking how to do it, it's a hard decision -- it means Java 17 requirement

**Comment by nicolo-paganin** [comment] 2023-01-03 13:35
Yes right, we are using it with java 17 and spring boot 3.0.0-M4 and it is working well.
It is not working starting from spring boot 3.0.0-M5 and the new releases.

**Comment by bartoszwalacik** [comment] 2023-01-03 14:28
I need to figure out if it's possible to bump Javers' dependencies to SpringBoot 3.0.0 and still have Java 8 target compatibility. I don't want to force all Javers users to move to Java 17. Any thought on this?

**Comment by nicolo-paganin** [comment] 2023-01-03 14:32
If we use Spring boot 3.0.0 o later versions the error is "no java beans found for Javers', it not happening with spring boot 3.0.0-M4.  I don't know why, I think we should understand why before, I think is not mandatory to have as requirement Java 17 as minimum version

**Comment by fatslo** [comment] 2023-01-04 13:09
I just have the same problem and stumbled across [this document](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide) while researching, it states:

> Spring Boot 2.7 introduced a new META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports file for registering auto-configurations, while maintaining backwards compatibility with registration in spring.factories. With this release, support for registering auto-configurations in spring.factories has been removed in favor of the imports file.

**Comment by yusufsahin** [comment] 2023-01-05 23:36
Maybe it is better to create brand new packages/lib to support spring boot 3.0.0?

**Comment by bartoszwalacik** [comment] 2023-01-06 06:44
It would mean more work for me when releasing , two main branches , each PR merged to both of them. I dont like this idea. Seems i must bump Java to 17 because some of my artifacts have dependencies on Spring's artifacts ...

**Comment by yusufsahin** [comment] 2023-01-08 16:39
You are right as you said Java 17 is required.sometimes is really hard to migrate Java major changes.

**Comment by smeligrana** [comment] 2023-01-13 10:45
Is there any news about when the spring boot 3 compatible version will be released ? Thanks

**Comment by bartoszwalacik** [comment] 2023-01-13 19:04
will try to put some work into it this weekend

**Comment by oguzyyilmaz** [comment] 2023-01-14 12:33
Many thanks. I am looking forward to your solution.

> will try to put some work into it this weekend

**Comment by bartoszwalacik** [comment] 2023-01-15 19:43
work in progress https://github.com/javers/javers/pull/1253

**Comment by bartoszwalacik** [comment] 2023-01-20 22:20
work in progress https://github.com/javers/javers/pull/1253/commits

**Comment by bartoszwalacik** [comment] 2023-01-22 08:23
released as 7.0.0-RC1, check it out

**Comment by oguzyyilmaz** [comment] 2023-01-22 09:05
I am trying that when I test Javers 7.0.0-RC1, the 'jv_snapshot' collection is created but no records are being written. Is there any additional configuration I need to do after the update?

Thanks.

**Comment by smeligrana** [comment] 2023-01-22 09:38
Hi,
   I tried to use it with spring-boot 3.0.2 and on startup it doesn't find the jaVers bean.

Thanks

**Comment by bartoszwalacik** [comment] 2023-01-22 09:44
@oguzyyilmaz nothing is changed in the configuration on the Javers side

@oguzyyilmaz @smeligrana please try to debug the issue. You can use this test case as an example https://github.com/javers/javers/blob/master/javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoStarterTest.groovy

**Comment by oguzyyilmaz** [comment] 2023-01-22 09:45
When I remove the bean that I wrote myself, I am also getting the error than smeligrana got. ("required a bean of type 'org.javers.core.Javers' that could not be found.")

My bean => 

@Configuration
@AllArgsConstructor
public class JaversConfiguration {

    private final MongoTemplate mongoTemplate;

    @Bean
    public Javers javers() {
        return JaversBuilder.javers()
                .registerJaversRepository(new MongoRepository(mongoTemplate.getDb()))
                .build();
    }
}

**Comment by bartoszwalacik** [comment] 2023-01-22 09:55
the problem must be replicated in a test case, you can start from running the test which I pointed out (requires docker)

**Comment by oguzyyilmaz** [comment] 2023-01-23 10:50
> @oguzyyilmaz nothing is changed in the configuration on the Javers side
> 
> @oguzyyilmaz @smeligrana please try to debug the issue. You can use this test case as an example https://github.com/javers/javers/blob/master/javers-spring-boot-starter-mongo/src/test/groovy/org/javers/spring/boot/mongo/JaversMongoStarterTest.groovy

Hi bartoszwalacik, 
I debugged using a test similar to the one you provided as an example and have reached the conclusion shared bellow.
![image](https://user-images.githubusercontent.com/13655776/214020320-22f61d9c-dc2a-45d4-9638-39c603e7aa6b.png)
There is no value associated with the Javers key in the cache map.

Thanks.

**Comment by shuairan** [comment] 2023-01-23 12:29
@bartoszwalacik the autoconfiguration setup files have a breaking change in spring boot 3: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files (spring.factories no longer supported)

**Comment by Gyomu** [comment] 2023-01-23 12:34
> @bartoszwalacik the autoconfiguration setup files have a breaking change in spring boot 3: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files (spring.factories file is no longer supported)

I confirm I had the same issue as @oguzyyilmaz where despite running, my spring application would not populate any javers commit.
Thinking it might be an autoconfiguration issue as @shuairan said, I just added this to my Application class:
```
@SpringBootApplication
@Import(JaversSqlAutoConfiguration.class)
public class Application {
```

and it started to work as with previous Spring Boot versions.

**Comment by Gyomu** [comment] 2023-01-23 14:13
You're welcome. Yet remember that this is just an ugly workaround to test and try to pinpoint the cause of the current autoconfiguration issue. Replacing `@AutoConfigureAfter` by `@AutoConfiguration(after=...)` and see if it solves everything (including the PostgreSQLDialect issue also).

**Comment by fatslo** [comment] 2023-01-24 02:15
> @bartoszwalacik the autoconfiguration setup files have a breaking change in spring boot 3: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files (spring.factories file is no longer supported)

I think it should suffice to replace the `META-INF/spring.factories` file in both the starter projects with the above mentioned new autoconfiguration file 
`META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports` with a slightly changed format.
See [here](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports) for an example

**Comment by smeligrana** [comment] 2023-01-31 18:10
How are the activities progressing?
I look forward to the new version.
Thanks

**Comment by bartoszwalacik** [comment] 2023-02-01 07:31
I plan to put some work into this issue On Friday. You are encouraged to contribute a PR with the fix to this branch `spring-boot-3-java-17`

**Comment by bartoszwalacik** [comment] 2023-02-02 21:38
thanks guys for your help in debugging, I will apply the fix suggested by @fatslo

**Comment by bartoszwalacik** [comment] 2023-02-02 22:03
https://github.com/javers/javers/commit/fd0057bdce92ee495300317daf1de2afc2273cbe
7.0.0-RC2 is on its way to Central

**Comment by shuairan** [comment] 2023-02-03 12:30
thank you, the auto-config is now working. 
but we are still expierencing the issue with the dialectMapper, so here is a PR for the dialects: https://github.com/javers/javers/pull/1262

**Comment by smeligrana** [comment] 2023-02-03 17:08
I also have the same problem, I think it is due to the test present in **org.javers.spring.boot.sql.DialectMapper** class where **hibernateDialect instanceof PostgreSQL81Dialect** is checked.

Thank you for the change to autoconfiguration.

**Comment by smeligrana** [comment] 2023-02-03 17:53
I tried the modification made by @shuairan and my application works correctly.

**Comment by bartoszwalacik** [comment] 2023-02-03 21:45
Thanks @shuairan, merged, releasing now, seems Javers needs better e2e tests for starters

**Comment by bartoszwalacik** [comment] 2023-02-04 08:16
7.0.0-RC3 should be in the Central soon, please check it out

**Comment by bartoszwalacik** [comment] 2023-02-05 09:49
7.0.0-RC3 is relesed

**Comment by bartoszwalacik** [comment] 2023-02-09 22:01
@smeligrana , @shuairan , @Gyomu does 7.0.0-RC3 work for you?

**Comment by Gyomu** [comment] 2023-02-10 08:57
AutoConfiguration seems to work, it breaks no tests anymore and the data is correctly persisted. LGTM.

**Comment by smeligrana** [comment] 2023-02-11 20:53
I have been using since it was released without any problems on a project using postgresql version 7.0.0-RC3. Thanks

**Comment by shuairan** [comment] 2023-02-14 10:07
Tested manually and run our unit tests and 7.0.0-RC3 works fine, thanks!

**Comment by bartoszwalacik** [comment] 2023-02-14 16:49
thanks guys, added this version to https://javers.org/release-notes

**Comment by SteveGT96** [comment] 2023-02-21 06:35
7.0.0-RC3 is working now but I'm facing another probleme !  Only the first object I create for each model is considered with the state INITIAL. Others  are being saved with the state UPDATE instead of INITIAL.
I tried manual commit and @JaversSpringDataAuditable way but I'm running into the same issue.

Expected behaviour: When I create an object for the first time, the state should be INITIAL. When I update an exisiting object, the state should be UPDATE.
![Screenshot 2023-02-21 072717](https://user-images.githubusercontent.com/45661418/220266042-185534af-5e8d-429e-894e-c22ccdd92428.png)

**Comment by SteveGT96** [comment] 2023-02-21 15:10
Manually tested 7.0.0-RC3 with Spring Boot 3.0.2 with MongoDB and kotlin, worked fine !

**Comment by yusufsahin** [comment] 2023-04-24 03:56
Can I kindly ask for v7 full release?

**Comment by bartoszwalacik** [comment] 2023-04-24 19:00
will try to release this week

**Comment by bartoszwalacik** [comment] 2023-04-24 19:41
https://github.com/javers/javers/pull/1253 merged

**Comment by bartoszwalacik** [comment] 2023-04-24 20:35
7.0.0 is released 
see https://javers.org/release-notes

**Closed by bartoszwalacik** 2023-04-24 20:35 UTC
Labels: fixed - waiting to be released
